# makefile for p1
# 16-311 Introduction to Robotics: Homework 0
# Hannah
#
# After navigating to your directory with your .h file, .c file, main file and  make file,
# you will type "make clean" to remove any previous executables, then "make",
# which will follow these instructions to compile and run your  code.
# Then enter ./p1 to run.

all:
	gcc -std=c99 -Wno-deprecated-declarations p1.c main.c -o p1

clean:
	rm -rf *~ p1